version: '2'
services:
  web:
    image: php:7
    command: php -S 0.0.0.0:8000 /app/index.html
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: fica.luandro.com
      LETSENCRYPT_HOST: fica.luandro.com
      LETSENCRYPT_EMAIL: luandro@gmail.com
    # command: wget --no-check-certificate -O master.zip $GIT_URL
