version: '3'
services:
  web:
    image: php:alpine
    volumes:
      - ./app:/var/www/html
    environment:
      VIRTUAL_HOST: fica.luandro.com
      LETSENCRYPT_HOST: fica.luandro.com
      LETSENCRYPT_EMAIL: luandro@gmail.com
    # command: wget --no-check-certificate -O master.zip $GIT_URL
